
package boopfest;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class AsignarGrupoAEscenario extends javax.swing.JFrame {

    /** Creates new form AsignarGrupoAEscenario */
    public AsignarGrupoAEscenario() throws SQLException {
        initComponents();
        
        ArrayList<String> nombresGrupos = bd.obtenerNombresGrupos();
        for(String nombre : nombresGrupos){
            this.cmbGrupos.addItem(nombre);
        }
        
        ArrayList<String> nombresFestivales = bd.obtenerNombresFestivales();
        for(String nombre : nombresFestivales){
            this.cmbFestival.addItem(nombre);
        }
        
        ArrayList<String> nombresEscenarios = bd.obtenerNombresEscenarios();
        for(String nombre : nombresEscenarios){
            this.cmbEscenarios.addItem(nombre);
        }
        /*
        String festivalSeleccionado = (String)this.cmbFestival.getSelectedItem();
        ArrayList<String> fechas = bd.obtenerFechasFestival(festivalSeleccionado);
        for(String f : fechas)
            this.cmbFecha.addItem(f);*/
        
        ArrayList<String> horas = obtenerHoras();
        for(String h : horas)
            this.cmbHoras.addItem(h);
        
    }
    
    public ArrayList<String> obtenerHoras(){
        ArrayList<String> horas = new ArrayList<String>();
        String hora;
            String min;
            for(int i=0 ; i<24 ; i++){
                hora="";
                if (i<10)
                    hora="0";
                
                hora+=Integer.toString(i);
                
                for(int j=0 ; j<2 ; j++){
                    if(j==0)
                        min="00";
                    else
                        min="30";
                    
                    horas.add(hora+":"+min);
                }
            }
        
        return horas;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        cmbGrupos = new javax.swing.JComboBox<>();
        cmbEscenarios = new javax.swing.JComboBox<>();
        cmbHoras = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbFestival = new javax.swing.JComboBox<>();
        txtDuracion = new javax.swing.JTextField();
        cmbFecha = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boop Fest");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Asignar grupo a escenario");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Grupo");

        jLabel3.setText("Escenario");

        jLabel4.setText("Hora");

        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel5.setText("Duración");

        jLabel6.setText("Festival");

        cmbFestival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFestivalActionPerformed(evt);
            }
        });

        txtDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionActionPerformed(evt);
            }
        });

        jLabel7.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnVolver)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                            .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbFecha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbGrupos, 0, 147, Short.MAX_VALUE)
                                .addComponent(cmbEscenarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbHoras, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbFestival, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDuracion)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbFestival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEscenarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnVolver))
                .addGap(20, 20, 20))
        );

        pack();
    }//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String idFestival = (String) this.cmbFestival.getSelectedItem();
        String grupo = (String) this.cmbGrupos.getSelectedItem();
        String idEscenario = (String) this.cmbEscenarios.getSelectedItem();
        String fecha = (String) this.cmbFecha.getSelectedItem();
        String hora = (String) this.cmbHoras.getSelectedItem();
        String duracion = this.txtDuracion.getText();
        
        try {
            bd.asignarGrupoAEscenario(idFestival, grupo, idEscenario, fecha, hora, duracion);
        } catch (SQLException e){
        }

        txtDuracion.setText("");
        duracionElegida = false;
        btnAceptar.setEnabled(false);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Principal ventana = new Principal();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cmbFestivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFestivalActionPerformed
        String festivalSeleccionado = (String)this.cmbFestival.getSelectedItem();
        //System.out.println(festivalSeleccionado);
        
        try {
            ArrayList<String> fechas = bd.obtenerFechasFestival(festivalSeleccionado);
            cmbFecha.removeAllItems();
            for(String fecha : fechas)
               this.cmbFecha.addItem(fecha);
        } catch (SQLException e){
        }
    }//GEN-LAST:event_cmbFestivalActionPerformed

    private void txtDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionActionPerformed
        if(!this.txtDuracion.getText().isEmpty())
            duracionElegida = true;
        
        if(duracionElegida)
            this.btnAceptar.setEnabled(true);
    }//GEN-LAST:event_txtDuracionActionPerformed
    
    /* private boolean festivalElegido = false;
    private boolean grupoElegido = false;
    private boolean escenarioElegido = false;
    private boolean horaElegida = false; */
    private boolean duracionElegida = false;
    //private String duracion = "";
    BaseDatos bd = new BaseDatos();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbEscenarios;
    private javax.swing.JComboBox<String> cmbFecha;
    private javax.swing.JComboBox<String> cmbFestival;
    private javax.swing.JComboBox<String> cmbGrupos;
    private javax.swing.JComboBox<String> cmbHoras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtDuracion;
    // End of variables declaration//GEN-END:variables

}
